# this is the github pages configuration file 
tile: CRCP 3320 Personal Site 
description: Cameron Tofani Personal Site 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one